function param = loadParams()
param.bandfilter = [10,500]; % lower and upper freq
param.lowfilter = 500;
param.highfilter = 10;
param.RMSwindow = 250;
%param.nbframe = 4000; % number frame needed (interpolation)
param.trials = 15;
param.trialDuration = 2000;
param.sampleRate = 600;
param.freq = 600;
param.mvc_duration = 3; % in seconds
param.mvc_trials = 4;
param.mvc_pause = 10; % seconds for rest between mvc trials
param.rec_pause = 3;
param.t_hold_force = 5;
param.t_relax = 10;
% param.method = 'low' ; % RMS ou low
param.channels = containers.Map;
param.channels('biceps') = 1;
param.channels('triceps') = 5;
end
